CREATE TABLE PROPRIETARIO (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(60) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    PRIMARY KEY(ID)
);

ALTER TABLE PROPRIETARIO ADD CONSTRAINT UK_PROPRIETARIO UNIQUE (EMAIL);